# catalog_config.yml (optional helper for your own reference)
catalog_prefix: RQ
width: 5
registry: catalog_registry.yml
base_prefix: APP
root: ./reqs
sep: '-'
created_date_field: created_date
digits: 3
itemformat: "yaml"
